import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('textbox', { name: 'Nom', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nom', exact: true }).fill('Her');
  await page.getByRole('textbox', { name: 'Nom', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Prénom' }).fill('test');
  await page.getByRole('textbox', { name: 'Prénom' }).press('Tab');
  await page.getByRole('textbox', { name: 'Téléphone' }).fill('06');
  await page.getByRole('textbox', { name: 'Téléphone' }).press('Tab');
  await page.getByRole('textbox', { name: 'Conseiller commercial (' }).fill('H');
  await page.getByRole('textbox', { name: 'Conseiller commercial (' }).press('Tab');
  await page.getByRole('button', { name: 'Démarrer le parcours' }).press('Enter');
  await page.getByRole('button', { name: 'Démarrer le parcours' }).click();
  await page.getByRole('textbox', { name: 'Ex: Assistant administratif,' }).click();
  await page.getByRole('textbox', { name: 'Ex: Assistant administratif,' }).fill('test');
  await page.locator('label').filter({ hasText: 'workSalarié' }).click();
  await page.getByText('Quotidiennement').first().click();
  await page.getByText('Savez-vous allumer un').click();
  await page.locator('label').filter({ hasText: 'Oui avec quelques difficultés' }).first().click();
  await page.locator('label').filter({ hasText: 'Oui' }).nth(2).click();
  await page.getByText('Occasionnellement').nth(1).click();
  await page.locator('label').filter({ hasText: 'Oui' }).nth(4).click();
  await page.getByText('Non').nth(3).click();
  await page.getByText('Occasionnellement').nth(2).click();
  await page.getByRole('button', { name: 'Valider mon profil' }).click();
  await page.getByRole('button', { name: 'description Excel' }).click();
  await page.getByText('ContinuerContinuerarrow_forward').click();
  await page.getByText('Une cellule').click();
  await page.locator('span').filter({ hasText: '=SOMME()' }).click();
  await page.getByText('Camembert (Secteur)').click();
  await page.getByRole('button', { name: 'Suivant arrow_forward' }).click();
  await page.locator('label').filter({ hasText: 'L\'icône : $' }).click();
  await page.getByText('A afficher les valeurs').click();
  await page.getByText('SI()').click();
  await page.getByText('conditionnelle').click();
  await page.getByText('AUJOURDHUI()').click();
  await page.getByRole('button', { name: 'Suivant arrow_forward' }).click();
  await page.locator('label').filter({ hasText: 'À effacer les valeurs ne ré' }).click();
  await page.locator('label').filter({ hasText: 'De copier et/ou incrémenter' }).click();
  await page.getByText('Un segment').click();
  await page.getByText('Données', { exact: true }).click();
  await page.getByText('Je protège le classeur').click();
  await page.getByRole('button', { name: 'Suivant arrow_forward' }).click();
  await page.getByRole('button', { name: 'Continuer' }).click();
  await page.getByRole('button', { name: 'Renforcement EXCEL' }).click();
  await page.getByRole('button', { name: 'Valider ce parcours et' }).click();
  await page.getByRole('combobox').selectOption('Je vise un emploi pour lequel de nouvelles compétences me seront utiles');
  await page.getByText('Non').first().click();
  await page.locator('label').nth(2).click();
  await page.getByRole('button', { name: 'Continuer arrow_forward' }).click();
  await page.getByText('Après-midi').click();
  await page.getByRole('button', { name: 'Valider mes disponibilités' }).click();
  await page.goto('http://localhost:5173/validation');
  await page.getByRole('button', { name: 'Oui, avec plaisir !' }).click();
  await page.getByRole('button', { name: 'Valider ce choix' }).click();
});