import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.pappers.fr/classements');
  await page.getByRole('link', { name: 'Deux-Sèvres (79)' }).click();
  await page.locator('div').filter({ hasText: 'Classement des entreprises :' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'RangEntrepriseActivitéChiffre' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'RangEntrepriseActivitéChiffre' }).nth(3).click();
  await page.getByRole('link', { name: 'IMA SA' }).click();
  await page.getByRole('heading', { name: 'IMA SA', exact: true }).dblclick();
  await page.getByRole('cell', { name: 'AVENUE DE PARIS, 79000 NIORT ' }).click();
  await page.getByRole('cell', { name: 'Activités des sociétés holding', exact: true }).click();
  await page.getByRole('cell', { name: 'Au moins 1 salarié (donnée' }).dblclick();
  await page.getByRole('cell', { name: '01/11/' }).click();
  await page.getByRole('rowheader', { name: 'Dirigeant :' }).click();
  await page.getByRole('cell', { name: 'Pino David' }).click();
  await page.getByRole('cell', { name: '281 025 ' }).click();
  await page.getByRole('cell', { name: '281 025 00017 ' }).click();
  await page.getByRole('cell', { name: 'SA à directoire (s.a.i.)' }).click();
  await page.getByRole('cell', { name: '382 784,00 €' }).click();
  await page.goto('https://www.pappers.fr/classements/aquitaine-limousin-poitou-charentes/deux-sevres');
  await page.getByRole('cell', { name: 'Au moins 1 salarié' }).first().click();
  await page.getByRole('cell', { name: 'Au moins 1 salarié' }).first().click();
  await page.getByRole('link', { name: 'SEOLIS' }).click();
  await page.getByRole('heading', { name: 'SEOLIS', exact: true }).dblclick();
  await page.getByRole('cell', { name: 'AVENUE DE PARIS, 79000 NIORT ' }).click();
  await page.getByRole('cell', { name: 'Commerce d\'électricité', exact: true }).click();
  await page.getByRole('cell', { name: 'Entre 100 et 199 salariés (' }).click();
  await page.getByRole('cell', { name: '/09/2006' }).click();
  await page.getByRole('cell', { name: 'Pilpay Yannick' }).click();
  await page.getByRole('cell', { name: '041 066 ' }).click();
  await page.getByRole('cell', { name: '041 066 00027 ' }).click();
  await page.getByRole('cell', { name: 'SA d\'économie mixte à' }).click();
  await page.getByRole('cell', { name: 'FR05492041066  ' }).click();
  await page.getByText('Gestion technique et').click();
  await page.getByRole('link', { name: 'Adilly (79200)' }).click();
  await page.getByRole('link', { name: 'AMALTIS' }).click();
  await page.locator('.close-btn').click();
  await page.getByRole('heading', { name: 'AMALTIS', exact: true }).click();
  await page.getByRole('cell', { name: 'RUE DE LA MARNE, 79200' }).click();
  await page.getByRole('cell', { name: 'Commerce de gros (commerce interentreprises) de produits chimiques', exact: true }).click();
  await page.getByRole('cell', { name: 'Entre 20 et 49 salariés (donn' }).click();
  await page.getByRole('cell', { name: '10/06/' }).click();
  await page.getByRole('cell', { name: 'Duquesnoy Gilles' }).click();
  await page.getByRole('cell', { name: '235 980 ' }).click();
  await page.getByRole('cell', { name: '235 980 00017 ' }).click();
  await page.getByRole('cell', { name: 'SAS, société par actions' }).click();
  await page.getByText('FABRICATION ACHAT EN VENTE D\'').click();
});